apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ot.fullname" . }}-docs
  labels:
    {{- include "ot.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  replicas: {{ .Values.docs.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: docs
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: docs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: docs
          image: "{{ .Values.docs.image.repository }}:{{ .Values.docs.image.tag }}"
          imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.docs.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.docs.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
