namespace: opentourney-staging

imagePullSecrets:
  - name: ghcr-pull

backend:
  image:
    tag: latest
    pullPolicy: Always
  replicas: 1

frontend:
  image:
    tag: latest
    pullPolicy: Always
  replicas: 1

docs:
  image:
    tag: latest
    pullPolicy: Always
  replicas: 1

percona:
  enabled: true
  clusterName: opentourney-staging-pg
  pgVersion: "16"
  storageSize: 1Gi
  backupStorageSize: 1Gi

secrets:
  oidcIssuer: "https://opentourney-staging.badconfig.com"
  oidcJwksUrl: "http://zitadel:8080/oauth/v2/keys"

zitadel:
  enabled: true
  externalDomain: "opentourney-staging.badconfig.com"
  externalSecure: true
  externalPort: 443
  login:
    publicBaseUri: "https://opentourney-staging.badconfig.com/ui/v2/login"

ingress:
  enabled: true
  hostname: "opentourney-staging.badconfig.com"
